### ISSUE TITLE
grad should be a `Tensor` instead of a `ndarray` (numpy array)

### ISSUE THREAD

**Issue by VIVelev** [VIVelev/nujo#23]
This will allow us to do high-order autodiff.

**Comment by VIVelev** [comment]
@ManiacMaxo can you address this? (in a separate branch though :D)

**Comment by ManiacMaxo** [comment]
affirmative

**Comment by samigeorgiev** [comment]
Mnogo profesionalno ;)

**Comment by VIVelev** [comment]
> Mnogo profesionalno ;)

Mn qsno, taka trqbva

**Comment by VIVelev** [comment]
Addressed in #26
